id: IB4889486
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:08:18+00:00'
last_modified: '2022-06-08T04:54:30.571406+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22407
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན། ༼རྡོ་པར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1B4E:
      image_group_id: I1KG22415
      title: ''
      total_pages: 644
      order: 1
      base_file: 1B4E.txt
    98EC:
      image_group_id: I1KG22416
      title: ''
      total_pages: 352
      order: 2
      base_file: 98EC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
